### ISSUE TITLE
Delete "Triage" and "Active" project workflows

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/.github#28]
Now that issues and PRs are automatically added to the new GitHub [Development](https://github.com/orgs/gocodebox/projects/18) project, can the workflow files that add to the old [Triage](https://github.com/orgs/gocodebox/projects/14) and [Active](https://github.com/orgs/gocodebox/projects/9) boards be removed from this project?
+ [`issue-triage.yml`](https://github.com/gocodebox/.github/blob/trunk/.github/workflows/issue-triage.yml)
+ [`pr-ready.yml`](https://github.com/gocodebox/.github/blob/trunk/.github/workflows/pr-ready.yml)

**Comment by thomasplevy** [comment]
Yes... In order to expedite cleanup, we'll want to modify the distribution workflow to facilitate bulk deletion of workflow files (to save us the effort of manually deleting these out of every project they've already been added to.

Conceivably we'll want to bulk-remove files in the future as well so building out a removal function will be beneficial longterm as well.

**Comment by thomasplevy** [comment]
https://github.com/gocodebox/.github/commit/9e3cc6edf7ddbbcdbc219c16b4258ea86ff9183a
