### ISSUE TITLE
Drop Create annotations job for the Lint JS workflow

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/.github#33]

**Comment by thomasplevy** [comment]
The eslint annotations aren't really necessary. I added them because I though they'd be helpful but in practice I think they're actually just annoying.

I think this is my stance at least.

Additionally, the annotations action requires access to repo secrets so PRs originating outside the organization will always cause the lint workflows to fail.

**Comment by thomasplevy** [comment]
I think we can safely remove the annotation step from the workflow: https://github.com/gocodebox/.github/blob/a2ff7ee0ee7d561afbd6f174fba74dbbeb2fc753/.github/workflow-templates/lint-js.yml#L50-L54

**Comment by thomasplevy** [comment]
https://github.com/gocodebox/.github/commit/51e9e23832e0b9c9ec4969e045885306bfd1db3e
